"$schema" = 'https://starship.rs/config-schema.json'

palette = "gruvbox_dark"

right_format = """
$cmd_duration
"""

format = """
$username$hostname$directory$git_branch$conda $character
"""

[palettes.gruvbox_dark]
rosewater = "#EBDBB2"
flamingo = "#F2E5BC"
pink = "#D3869B"
mauve = "#B16286"
red = "#FB4934"
maroon = "#CC241D"
peach = "#FE8019"
yellow = "#FABD2F"
green = "#B8BB26"
teal = "#8EC07C"
sky = "#83A598"
sapphire = "#458588"
blue = "#83A598"
lavender = "#D79921"
text = "#EBDBB2"
subtext1 = "#D5C4A1"
subtext0 = "#BDAE93"
overlay2 = "#A89984"
overlay1 = "#928374"
overlay0 = "#7C6F64"
surface2 = "#665C54"
surface1 = "#504945"
surface0 = "#3C3836"
base = "#1D2021"
mantle = "#191D1E"
crust = "#141617"

[git_branch]
format = " [\\[$symbol$branch\\]](rosewater)"
symbol = " "

[git_status]
disabled = true

[git_metrics]
disabled = true

[directory]
read_only = " "
style = "fg:yellow "
# truncation_length = 6
# truncation_symbol = " ••/"
fish_style_pwd_dir_length = 1
format = '[󰉋 $path]($style)'

[cmd_duration]
min_time = 2000                           # only show if > 2 s
format = " took [$duration](bold yellow)"

[character]
success_symbol = "[ ](bold fg:blue)"
error_symbol = "[  ](bold fg:red)"
vimcmd_symbol = "[](bold fg:green)"
