# --- Gruvbox Dark

FAST_HIGHLIGHT_STYLES[default]="fg=#EBDBB2"
FAST_HIGHLIGHT_STYLES[command]="fg=#83A598,bold"
FAST_HIGHLIGHT_STYLES[builtin]="fg=#8EC07C,bold"
FAST_HIGHLIGHT_STYLES[alias]="fg=#B8BB26,bold"
FAST_HIGHLIGHT_STYLES[function]="fg=#D3869B"
FAST_HIGHLIGHT_STYLES[parameter]="fg=#FABD2F"
FAST_HIGHLIGHT_STYLES[option]="fg=#D79921"
FAST_HIGHLIGHT_STYLES[path]="fg=#8EC07C,underline"
FAST_HIGHLIGHT_STYLES[quote]="fg=#D3869B"
FAST_HIGHLIGHT_STYLES[double-quoted-argument]="fg=#D3869B"
FAST_HIGHLIGHT_STYLES[single-hyphen-option]="fg=#EBDBB2"
FAST_HIGHLIGHT_STYLES[double-hyphen-option]="fg=#EBDBB2"
FAST_HIGHLIGHT_STYLES[comment]="fg=#928374,italic"
FAST_HIGHLIGHT_STYLES[unknown-token]="fg=#FB4934,bold"
FAST_HIGHLIGHT_STYLES[separator]="fg=#665C54"
FAST_HIGHLIGHT_STYLES[redirection]="fg=#FE8019"
FAST_HIGHLIGHT_STYLES[history-expansion]="fg=#FABD2F,bold"
FAST_HIGHLIGHT_STYLES[dollar-double-quoted-argument]="fg=#B8BB26"
